apiVersion: v1
kind: Secret
metadata:
  name: sharepoint-credentials
type: Opaque
stringData:
  # Populate with your real values or create with kubectl (see README)
  DSXCONNECTOR_SP_TENANT_ID: ""
  DSXCONNECTOR_SP_CLIENT_ID: ""
  DSXCONNECTOR_SP_CLIENT_SECRET: ""

