apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dsx-connect-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: dsx-connect.127.0.0.1.nip.io # nip.io is a public DNS server that maps special hostnames like anything.127.0.0.1.nip.io to 127.0.0.1 - great for local testing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dsx-connect-api
                port:
                  number: 8586
