apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dsx-connect-api
spec:
  to:
    kind: Service
    name: dsx-connect-api
  port:
    targetPort: 8586
  tls:
    termination: edge
  wildcardPolicy: None
