services:
  dsx_connect_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8586:8586"
    environment:
      - PYTHONUNBUFFERED=1
      - DSXCONNECT_TASKQUEUE__BROKER=redis://redis:6379/0
      - DSXCONNECT_TASKQUEUE__BACKEND=redis://redis:6379/0
      - DSXCONNECT_DATABASE__TYPE=tinydb
      - DSXCONNECT_DATABASE__LOC=data/dsx-connect.db.json
      - DSXCONNECT_DATABASE__RETAIN=100
      - DSXCONNECT_SCANNER__SCAN_BINARY_URL=http://dsxa_scanner:5000/scan/binary/v2
      - LOG_LEVEL=debug
    depends_on:
      - redis
    networks:
      dsx-network:
        aliases:
          - dsx-connect-api # this is the name connectors will use to connect to the dsx_connect_core service API on the dsx-connect-network docker network
    command: uvicorn dsx_connect.app.dsx_connect_api:app --host 0.0.0.0 --port 8586

  dsx_connect_workers:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - DSXCONNECT_TASKQUEUE__BROKER=redis://redis:6379/0
      - DSXCONNECT_TASKQUEUE__BACKEND=redis://redis:6379/0
      - DSXCONNECT_SCANNER__SCAN_BINARY_URL=http://dsxa_scanner:5000/scan/binary/v2
      - DSXCONNECT_SCAN_RESULT_TASK_WORKER__SYSLOG_SERVER_URL=rsyslog
      - DSXCONNECT_SCAN_RESULT_TASK_WORKER__SYSLOG_SERVER_PORT=514
    depends_on:
      - redis
      - rsyslog
    networks:
      - dsx-network
    command: celery -A dsx_connect.taskqueue.celery_app worker --loglevel=info -Q scan_request_queue,verdict_action_queue,scan_result_queue --concurrency=1

  redis:
    image: redis:6
    networks:
      - dsx-network

  rsyslog:
    image: rsyslog/syslog_appliance_alpine:latest
    networks:
      - dsx-network

# The following assumes an already created docker network like this:
# docker network create dsx-connect-network --driver bridge
networks:
  dsx-network:
    external: true
    name: dsx-connect-network  # change this to an existing docker network