version: "3.8"
services:
  dsx_connect_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8586:8586"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis1
    networks:
      - dsx-network
    command: uvicorn dsx_connect.app.dsx_connect_app:app --host 0.0.0.0 --port 8080

networks:
  dsx-network:
    driver: bridge