{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "syslog.fullname" . }}
  labels:
    {{- include "syslog.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "syslog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "syslog.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: syslog
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: UDP # Syslog typically uses UDP
{{- end }}
