{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: syslog
spec:
  selector:
    app: syslog
  type: {{ .Values.service.type }}
  ports:
    - protocol: UDP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
{{- end }}