image:
  repository: dsxconnect/dpa-rocky9
  tag: "4.1.0.2131"
  pullPolicy: IfNotPresent

service:
  port: 5000

env:
  APPLIANCE_URL: "selab-dpa.customers.deepinstinctweb.com"
  TOKEN: "7b2b872c-632f-4220-ac42-7b2c5a76850a"
  SCANNER_ID: "81"
  FLAVOR: "rest,config"
  NO_SSL: "true"
