replicaCount: 1

image:
  repository: rsyslog/rsyslog
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  tcpPort: 514
  udpPort: 514
  enableUDP: true

resources: {}

config:
  writeToStdout: true
  writeToFile: false
  filePath: /var/log/dsx.log

  hec:
    enabled: false
    host: "splunk.example.com"
    port: 8088
    usehttps: true
    restpath: "/services/collector"
    token: ""

  forward:
    enabled: false
    target: "siem.example.com"
    port: 6514
    tls: true
    permittedPeer: "siem.example.com"
