{{- if .Values.ingressWebhook.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "onedrive-connector.fullname" . }}-webhook
  labels:
    {{- include "onedrive-connector.labels" . | nindent 4 }}
  {{- with .Values.ingressWebhook.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingressWebhook.className }}
  ingressClassName: {{ .Values.ingressWebhook.className }}
  {{- end }}
  {{- if .Values.ingressWebhook.tls }}
  tls:
    {{- toYaml .Values.ingressWebhook.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingressWebhook.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /{{ include "onedrive-connector.routeBase" $ }}/webhook/event
            pathType: Prefix
            backend:
              service:
                name: {{ include "onedrive-connector.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
{{- end }}
