apiVersion: v1
kind: Service
metadata:
  name: {{ include "onedrive-connector.fullname" . }}
  labels:
    {{- include "onedrive-connector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8660
      protocol: TCP
      name: http
  selector:
    {{- include "onedrive-connector.selectorLabels" . | nindent 4 }}
