{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dsxa-scanner.fullname" . }}
spec:
  selector:
    app: {{ include "dsxa-scanner.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
{{- end }}
