apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rsyslog.fullname" . }}
  labels:
    {{- include "rsyslog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rsyslog.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rsyslog.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp-syslog
              containerPort: {{ .Values.service.tcpPort }}
              protocol: TCP
            {{- if .Values.service.enableUDP }}
            - name: udp-syslog
              containerPort: {{ .Values.service.udpPort }}
              protocol: UDP
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/rsyslog.conf
              subPath: rsyslog.conf
            - name: varlog
              mountPath: /var/log
          readinessProbe:
            tcpSocket:
              port: tcp-syslog
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: tcp-syslog
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: {{ include "rsyslog.fullname" . }}-config
        - name: varlog
          emptyDir: {}

