# Note - this values get overridden when deploying at the top of the helm chart.  These values are used only
# installing the sub chart, dsx-connect-api
enabled: true

image:
  repository: logangilbert/dsx-connect
  tag: "0.1.34"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8586

resources: {}

env:
  DSXCONNECT_RESULTS_DATABASE__TYPE: tinydb
  DSXCONNECT_RESULTS_DATABASE__LOC: data/dsx-connect.db.json
  DSXCONNECT_RESULTS_DATABASE__RETAIN: 100
  DSXCONNECT_SCANNER__SCAN_BINARY_URL: http://dsxa-scanner:5000/scan/binary/v2
  DSXCONNECT_TASKQUEUE__BROKER: redis://redis:6379/0
  DSXCONNECT_TASKQUEUE__BACKEND: redis://redis:6379/0
  LOG_LEVEL: debug