# Note - this values get overridden when deploying at the top of the helm chart.  These values are used only
# installing the sub chart, dsx-connect-api
enabled: true

image:
  repository: dsxconnect/dsx-connect
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8586

tls:
  enabled: false
  port: 443
  secretName: ""
  mountPath: /app/certs

resources: {}

env:
  DSXCONNECT_RESULTS_DATABASE__TYPE: tinydb
  DSXCONNECT_RESULTS_DATABASE__LOC: data/dsx-connect.db.json
  DSXCONNECT_RESULTS_DATABASE__RETAIN: 100
  DSXCONNECT_TASKQUEUE__BROKER: redis://redis:6379/0
  DSXCONNECT_TASKQUEUE__BACKEND: redis://redis:6379/0
  LOG_LEVEL: debug
