# Note - this values get overridden when deploying at the top of the helm chart.  These values are used only
# installing the sub chart, dsx-connect-api
enabled: true

image:
  repository: dsxconnect/dsx-connect
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8586

tls:
  enabled: false
  port: 443
  secretName: ""
  mountPath: /app/certs

resources: {}

env:
  DSXCONNECT_RESULTS_DB: redis://redis:6379/3
  DSXCONNECT_RESULTS_DB__RETAIN: 100
  DSXCONNECT_WORKERS__BROKER: redis://redis:6379/5
  DSXCONNECT_WORKERS__BACKEND: redis://redis:6379/6
  LOG_LEVEL: debug
