{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "salesforce-connector.fullname" . }}-ingress
  labels:
    {{- include "salesforce-connector.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "salesforce-connector.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      {{- range .Values.networkPolicy.allowFrom }}
      - {{- toYaml . | nindent 8 }}
      {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
        {{- if .Values.tls.enabled }}
        - protocol: TCP
          port: 443
        {{- end }}
{{- end }}
