enabled: true

image:
  repository: dsxconnect/dsx-connect
  tag: ""
  pullPolicy: IfNotPresent

replicaCount: 1

env:
  LOG_LEVEL: debug

celery:
  # queue computed from DSXCONNECT_APP_ENV in template unless overridden here
  # queue: "dev.dsx_connect.scans.verdict"
  concurrency: 1

hpa:
  enabled: false
  # minReplicas defaults to replicaCount when omitted
  # minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
