enabled: true

image:
  repository: dsxconnect/dsx-connect
  tag: "__VERSION__"
  pullPolicy: IfNotPresent

env:
  LOG_LEVEL: debug

celery:
  # queue computed from DSXCONNECT_APP_ENV in template unless overridden here
  # queue: "dev.dsx_connect.scans.verdict"
  concurrency: 1
