apiVersion: v2
name: dsx-connect-chart
description: A Helm chart for Kubernetes
type: application
version: 0.3.47
appVersion: "0.3.47"
dependencies:
  - name: redis
    version: 0.1.0
    repository: file://charts/redis
  - name: rsyslog
    version: 0.1.0
    repository: file://charts/rsyslog
    condition: rsyslog.enabled
  - name: dsxa-scanner
    version: 0.1.0
    repository: file://charts/dsxa-scanner
