apiVersion: v1
kind: Service
metadata:
  name: {{ include "sharepoint-connector.fullname" . }}
  labels:
    {{- include "sharepoint-connector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.tls.enabled }}
    - port: {{ .Values.tls.port }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "sharepoint-connector.selectorLabels" . | nindent 4 }}

